name: CI-CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
      - unlabeled
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  FRONTEND:
    uses: Strongminds/signals-frontend/.github/workflows/build_and_push_to_docker_hub.yml@main
    with:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  DEV:
    uses: Strongminds/signals-aws-infrastructure/.github/workflows/cdk.template.yml@main
    with:
      ENVIRONMENT: dev
      DOMAIN: signalen.dev.os2.strongminds.dk
      AWS_ACCOUNT_ID: 816069162453
      SUB_TREE_PATH: "aws-infrastructure/"
    secrets: inherit


